name: NexusUHC
version: 1.0
author: MarcoDesignerMC
main: me.timer.bukkit.MainClass
commands:
  timer:
    description: see all commands options
permissions:
  canStartTimer:
    description: Can start the UHC timer